# Generated by Django 5.2.5 on 2025-08-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velo_app', '0004_remove_calorietracker_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitytrackerlog',
            name='activity_type',
            field=models.CharField(choices=[('Workout', 'Workout Session'), ('steps', 'Steps')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='workout_type',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength Training'), ('flexibility', 'Flexibility'), ('balance', 'Balance Training'), ('pilates', 'Pilates'), ('yoga', 'Yoga'), ('running', 'Running'), ('walking', 'Walking'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('hiking', 'Hiking'), ('gym', 'Gym Workout')], max_length=50, null=True),
        ),
    ]
