# Generated by Django 5.2.5 on 2025-08-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velo_app', '0005_remove_userprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytrackerlog',
            name='steps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activitytrackerlog',
            name='activity_type',
            field=models.CharField(choices=[('workout', 'Workout'), ('steps', 'Steps')], max_length=50, null=True),
        ),
    ]
