# Generated by Django 5.2.5 on 2025-08-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velo_app', '0006_activitytrackerlog_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fitness_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50, null=True),
        ),
    ]
