# Generated by Django 5.2.5 on 2025-08-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velo_app', '0007_userprofile_fitness_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='weight',
            new_name='current_weight',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
