# Generated by Django 5.2.5 on 2025-08-31 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velo_app', '0008_rename_weight_userprofile_current_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealtracker',
            name='user',
        ),
        migrations.RemoveField(
            model_name='minutetracker',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='weightentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='user',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='MealTracker',
        ),
        migrations.DeleteModel(
            name='MinuteTracker',
        ),
        migrations.DeleteModel(
            name='TrainingPlan',
        ),
        migrations.DeleteModel(
            name='WeightEntry',
        ),
        migrations.DeleteModel(
            name='WorkoutSession',
        ),
    ]
